### ISSUE TITLE
[BUG] segmentation fault when running with targetHandler 

### ISSUE THREAD

**Issue by minimum-sauce** [acoustic-warfare/beamforming-lk#97]
aw_control_unit crashes with segfault when running beamformer.

``` 
Starting program: /usr/src/app/build/beamformer
warning: Error disabling address space randomization: Operation not permitted
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
__strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:74
74      ../sysdeps/x86_64/multiarch/strlen-avx2.S: No such file or directory.
(gdb) bt
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:74
#1  0x000061ba1636250c in std::char_traits<char>::length(char const*) (__s=0x0) at /usr/include/c++/11/bits/char_traits.h:399
#2  std::basic_string_view<char, std::char_traits<char> >::basic_string_view(char const*) (__str=0x0, this=<optimized out>) at /usr/include/c++/11/string_view:132
#3  TargetHandler::TargetHandler(gps_data_t*) (gpsData=0x7ffeafbb57e8, this=0x7ffeafbbb7b8) at /usr/src/app/src/WaraPS/target_handler.h:38
#4  AWControlUnit::AWControlUnit() (this=0x7ffeafbb4d20) at /usr/src/app/src/aw_control_unit.cpp:99
#5  0x000061ba163539e5 in main() () at /usr/src/app/src/main.cpp:8
```

## reproduce
1. checkout commit "13d6ab3669ec006" in branch rtmp_streamer 
2. build docker container
3. run docker container with ./start.sh
4. build program with 
```
cd build
cmake -DCMAKE_BUILD_TYPE=Debug ..
cmake --build -j$(nproc)
```
5. run ./beamformer with gdb or without

**Comment by tuvabjornberg** [comment]
Löstes inte detta med [a98dce5](https://github.com/acoustic-warfare/beamforming-lk/pull/93/commits/a98dce5f0d55f023c5cae4b3e3ea4bcdf1658652)?
Alltså, dra bara ner det senaste från dev eller main.
